baseurl = "github.com/ashish-brahma/portfolio"
title = "Ashish Brahma"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
  pagerSize = 20

[markup.highlight]
  style = "github-dark"

[markup.goldmark.renderer]
  unsafe = true

[imaging]
  quality = 90

[params]
  HeadTitle = "Ashish Brahma | Personal homepage - Apple Developer"
  author = "Ashish Brahma"
  info = "Apple Developer"
  description = "Ashish Brahma's personal homepage"
  keywords = "blog,developer,personal"
  avatarurl = "images/ashish-2022.jpg"

  faviconSVG = "images/favicon.svg"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 1
  url = "mailto:ashish.brahma@outlook.com"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/brahma-ashish"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 3
  url = "https://github.com/ashish-brahma/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 4
  url = "https://x.com/b_ashish_3535"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 5
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
 [[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
